export const UPDATE_AUTH = "UPDATE_AUTH";
export const USER_DETAIL = "USER_DETAIL";
export const UPDATE_USER_PROGRAM_COUNT = "UPDATE_USER_PROGRAM_COUNT";

export const ADDRESS_MANAGE = "ADDRESS_MANAGE";
export const FORGET_PASS_VALID = "FORGET_PASS_VALID";

export const UPDATE_WELLNESS_QUESTIONS = "UPDATE_WELLNESS_QUESTIONS";
export const UPDATE_NUTRITION_CALCULATOR = "UPDATE_NUTRITION_CALCULATOR";

export const UPDATE_PROGRAM = "UPDATE_PROGRAM";
export const UPDATE_CALENDAR = "UPDATE_CALENDAR";
export const MANAGE_FITNESS = "MANAGE_FITNESS";
export const MARK_WORKOUT_FAVOURITE = "MARK_WORKOUT_FAVOURITE";
export const LIVE_WORKOUT_FAVOURITE = "LIVE_WORKOUT_FAVOURITE";
export const MARK_WORKOUT_DETAILS_FAVOURITE = "MARK_WORKOUT_DETAILS_FAVOURITE";
export const TODAY_WORKOUT_FAVOURITE = "TODAY_WORKOUT_FAVOURITE";
export const SEARCH_ACTION = "SEARCH_ACTION";
export const MANUAL_WORKOUT = "MANUAL_WORKOUT";
export const MANAGE_RECIPES = "MANAGE_RECIPES";
export const MARK_RECIPE_FAVOURITE = "MARK_RECIPE_FAVOURITE";
export const FILTER_MANAGE = "FILTER_MANAGE";
export const MANAGE_VIDEO_STREAM = "MANAGE_VIDEO_STREAM";

export const ALL_CHALLENGES = "ALL_CHALLENGES";
export const CHALLENGES_DETAILS = "CHALLENGES_DETAILS";
export const DASHBOARD_CHALLENGE = "DASHBOARD_CHALLENGE";

export const GET_MYPLAN_SIDE_BAR = " GET_MYPLAN_SIDE_BAR";
export const RECOMMENDED_RECIPE = "RECOMMENDED_RECIPE"

export const FAV_TODAY_RECIPE = "FAV_TODAY_RECIPE";
export const GET_COACH = "GET_COACH";
export const COACH_WORKOUT_FAVOURITE = "COACH_WORKOUT_FAVOURITE";

export const STRIPE_PUBLISHABLE_KEY="pk_test_51LaCtHSGbveZoLhX4iUMYjv2mYFpEOaGaXwZR4YdMz9Hh3lgLIr46Xaqqsh94ULMMsbE97IbEoveq1py7PkyhY8i00NG8KsSY0";
export const STRIPE_SECRET_KEY="sk_test_51LaCtHSGbveZoLhXvugxyPsvNtR01tvQmvwvRv1LaqdKuIAbw3tiHVaLjCQsHNYwanjHALn5BKeTMSYoi0uFhwrk00NOE24TbZ"

